### ISSUE TITLE
add AI Game Jam

### ISSUE THREAD

**Issue by bukki** [leafo/compohub#113]
details:
http://ai-jam.com/
http://itch.io/jam/ai-game-jam

Dates: March 22-29, 2015

{
      "name": "AI Game Jam",
      "url": "http://ai-jam.com/",
      "start_date": "2015-03-20 21:00:00",
      "end_date": "2015-03-29 20:59:59"
}

**Comment by 0x0961h** [comment]
I added it to 2015.json. Now need to poke Leaf to deploy it to CompoHub.

**Comment by leafo** [comment]
it's deployed
